sudo: required
services: 
    - docker 

before_install:
    - docker build -t rahulalishetty/react-test -f Dockerfile.dev .

script:
    - docker run rahulalishetty/react-test npm run test -- --coverage