sudo: required
services: 
    - docker 

before_install:
    - docker build -t rahulalishetty/react-test -f Dockerfile.dev .

script:
    - docker run -e CI=true rahulalishetty/react-test npm run test -- --coverage