sudo: required
services: 
    - docker 

before_install:
    - docker build -t rahulalishetty/react-test -f Dockerfile.dev .

script:
    - docker run -e CI=true rahulalishetty/react-test npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-066361185434"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY