version: '3'
services:
  ui:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /dir/node_modules
      - .:/dir
  
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /dir/node_modules
      - .:/dir
    command: ["npm", "run", "test"]